from PyQt5 import QtCore, QtGui, QtWidgets
from pytube import YouTube
import os
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(252, 95)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 0, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(0, 30, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(0, 50, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 70, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(100, 70, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Link:"))
        self.checkBox.setText(_translate("MainWindow", "Video"))
        self.checkBox_2.setText(_translate("MainWindow", "Music"))
        self.pushButton.setText(_translate("MainWindow", "Download"))
        self.pushButton.clicked.connect(self.download)

    def download(self):
        if self.checkBox.isChecked()==1:
            youtubeObject = YouTube(self.lineEdit.text())
            self.progressBar.setProperty("value", 33)
            youtubeObject = youtubeObject.streams.get_highest_resolution()
            self.progressBar.setProperty("value", 66)
            youtubeObject.download()
            self.progressBar.setProperty("value", 100)
            self.progressBar.setProperty("value", 0)
        if self.checkBox_2.isChecked()==1:
            yt = YouTube(self.lineEdit.text())
            self.progressBar.setProperty("value", 16)
            video = yt.streams.filter(only_audio=True).first()
            self.progressBar.setProperty("value", 32)
            out_file = video.download()
            self.progressBar.setProperty("value", 48)
            base, ext = os.path.splitext(out_file)
            self.progressBar.setProperty("value", 60)
            new_file = base + '.mp3'
            self.progressBar.setProperty("value", 76)
            os.rename(out_file, new_file)
            self.progressBar.setProperty("value", 100)
            self.progressBar.setProperty("value", 0)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
